version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/services"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps):"
    
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps):"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps):"

  - package-ecosystem: "pub"
    directory: "/mobile"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "permission_handler"
        versions: [">= 12.0.0"]
      - dependency-name: "google_fonts"
        versions: [">= 9.0.0"]